version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVICES=auth:http://auth:8081,device-registry:http://device-registry:8082
    volumes:
      - ./.env:/app/.env

  # Mock services pentru testing
  auth-service:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./mock-services/auth:/usr/share/nginx/html

  device-registry-service:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./mock-services/device-registry:/usr/share/nginx/html

volumes:
  redis_data: